# Generated by Django 5.0.3 on 2024-03-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='typ',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
