# Generated by Django 5.0.3 on 2024-03-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_typ'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieData',
        ),
    ]
